name: reviewdog
on: [pull_request]
jobs:
  # Use shellcheck to lint shell scripts
  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
  # Use misspell to correct spelling mistakes
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
  # Use yamllint to lint yaml files
  yamllint:
    name: check / yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true
          yamllint_flags: '-d "{extends: default, rules: {truthy: disable}}" .'
  # Use dotenv-liknter to lint dotenv files
  dotenv-linter:
    name: runner / dotenv-linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run dotenv-linter
        uses: dontenv-linter/action-dotenv-linter@v2.18.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check
          fail_on_error: true
          dotenv_linter_flags: --skip UnorderedKey,LowercaseKey
